### ISSUE TITLE
Ideas for more creative and fitting title for this repo

### ISSUE THREAD

**Issue by 0xDeadcell** [0xDeadcell/toggle-hide-windows#2]
I'm terrible with names, looking for some ideas that fit the purpose of this project more accurately... Which is to show custom user backgrounds after idle, and lock the desktop if specified.

**Comment by janandraczko** [comment]
Maybe these will suit you:

imagepic
styline
imagicbox
imagepin
imagic
lockedpic
lockart
imagecave
imaget
lockimage
imagecarg
imagewall
